In [3]:
import pandas as pd 
import numpy as np

In [4]:
Train = pd.read_csv('train.csv')
Train.head()

sentiment                                            message  tweetid
0          1  PolySciMajor EPA chief doesn't think carbon di...   625221
1          1  It's not like we lack evidence of anthropogeni...   126103
2          2  RT @RawStory: Researchers say we have three ye...   698562
3          1  #TodayinMaker# WIRED : 2016 was a pivotal year...   573736
4          1  RT @SoyNovioDeTodas: It's 2016, and a racist, ...   466954

In [5]:
Train.isnull().sum()

sentiment    0
message      0
tweetid      0
dtype: int64

In [6]:
blanks = []
for i,sent,msg,twId in Train.itertuples():
    if type(msg)==str:
        if msg.isspace():
            blanks.append(i)

In [7]:
blanks

[]

In [8]:
Train.iloc[0]['message']

"PolySciMajor EPA chief doesn't think carbon dioxide is main cause of global warming and.. wait, what!? https://t.co/yeLvcEFXkC via @mashable"

In [9]:
def extract_hashtags(df):
    # your code here
    g = df['message'].str.findall(r'@.*?(?=\s|$)')
    df['@mentions'] = g.apply(lambda x: ','.join(x).lower().split(',') if len(x) > 0 else np.nan)
    df["message"]= df['message'].apply(lambda x: ''.join(x) if len(x) > 0 else np.nan)
    df['hashtags'] = df['message'].str.findall(r'#.*?(?=\s|$)')
    df["hashtags"]= df['hashtags'].apply(lambda x: ','.join(x).lower().split(',') if len(x) > 0 else np.nan)
    
    return df

In [10]:
extract_hashtags(Train)

sentiment                                            message  tweetid  \
0              1  PolySciMajor EPA chief doesn't think carbon di...   625221   
1              1  It's not like we lack evidence of anthropogeni...   126103   
2              2  RT @RawStory: Researchers say we have three ye...   698562   
3              1  #TodayinMaker# WIRED : 2016 was a pivotal year...   573736   
4              1  RT @SoyNovioDeTodas: It's 2016, and a racist, ...   466954   
5              1  Worth a read whether you do or don't believe i...   425577   
6              1  RT @thenation: Mike Pence doesn’t believe in g...   294933   
7              1  RT @makeandmendlife: Six big things we can ALL...   992717   
8              1  @AceofSpadesHQ My 8yo nephew is inconsolable. ...   664510   
9              1  RT @paigetweedy: no offense… but like… how do ...   260471   
10             1  RT @StephenSchlegel: she's thinking about how ...   295793   
11             1  I do hope people who are vocal about climate c...   763719   
12             2  RT @tveitdal: We only have a 5 percent chance ...   454673   
13             1  RT @Alifaith55: Oh. My. God.\n\nTrump's Govern...    41161   
14             2  Fossil fuel giant ExxonMobil ‘misled’ the publ...   658092   
15             1  RT @GlblCtzn: 'I don't wanna live forever – an...   319524   
16             1  RT @jackholmes0: Issues scrubbed from https://...   698009   
17             1  RT @patagonia: If our elected leaders fail to ...   490604   
18             1  RT @SenSanders: We have a president-elect who ...   228658   
19             0  Calum: *tweets abt reunitingish w the cast*\n-...   547924   
20             1  RT @c40cities: 46 C40 Mayors, representing 250...   625014   
21             1  RT @World_Wildlife: How climate change impacts...   690605   
22             0  we also met this guy, he let us in on some tru...    67545   
23             1  https://t.co/KyNIBjmDk5\nScientists say climat...   567842   
24             1  RT @TammyGrubb: Obama raises climate change. Y...   684492   
25             1  I hate to say this, but *mental* health will b...   438578   
26             2  Bangladesh confronting climate change head on ...   365291   
27             1  Hey There! Michael's vetted and approved marke...   387685   
28            -1  Sally Kohn’s latest evidence of climate change...   355491   
29             1  RT @StarTalkRadio: First: The public understan...   354015   
...          ...                                                ...      ...   
15789          1  Denying evidence of climate change is like fin...   530499   
15790          1  RT @CleanAirMoms_FL: .@DCCC fighting climate c...   618837   
15791          0  He is Instagramming about the dangers of globa...   410790   
15792          1  Trumps actions on climate change are an assaul...   970642   
15793          2  Suicides of nearly 60000 Indian farmers linked...     5456   
15794          1  Denying climate change is real, but so is dang...    62737   
15795          2  China’s coal use drops, showing commitment to ...   150587   
15796          2  RT @BreBarra: It's time to give up climate cha...   983654   
15797          0  @realDonaldTrump Damn China &amp; their climat...   650825   
15798          1  Dams raise global warming gas: SciDev https://...   863077   
15799          1  RT @SethMacFarlane: HRC proposes installing ha...    52528   
15800          1  RT @sapinker: The only practical way to avert ...   580806   
15801          1  RT @SenSanders: On virtually every major issue...   331127   
15802          2  Michael Bloomberg to world leaders: ignore Tru...   585908   
15803          2  Suicides of nearly 60,000 Indian farmers linke...   296403   
15804          1  RT @cathdweeb: me with full knowledge of globa...   386076   
15805          2  RT @GrindTV: New head of EPA says climate chan...   830383   
15806         -1  RT @HerberMp: @sness5561_ness Al Gore is a idi...   213863   
15807  

In [11]:
Train['sentiment'].value_counts()

 1    8530
 2    3640
 0    2353
-1    1296
Name: sentiment, dtype: int64

In [12]:
contractions = {
"ain't": "are not","aren't": "are not","can't": "cannot","can't've": "cannot have",
"'cause": "because","could've": "could have","couldn't": "could not","couldn't've": "could not have","didn't": "did not",
"doesn't": "does not",
"don't": "do not",
"hadn't": "had not",
"hadn't've": "had not have",
"hasn't": "has not",
"haven't": "have not",
"he'd": "he would",
"he'd've": "he would have",
"he'll": "he will",
"he'll've": "he shall have / he will have",
"he's": "he is",
"how'd": "how did",
"how'd'y": "how do you",
"how'll": "how will",
"how's": "how is",
"i'd": "I would",
"i'd've": "I would have",
"i'll": "I will",
"i'll've": "I shall have / I will have",
"i'm": "I am",
"i've": "I have",
"isn't": "is not",
"it'd": "it had",
"it'd've": "it would have",
"it'll": "it will",
"it'll've": "it shall have / it will have",
"it's": "it is",
"let's": "let us",
"ma'am": "madam",
"mayn't": "may not",
"might've": "might have",
"mightn't": "might not",
"mightn't've": "might not have",
"must've": "must have",
"mustn't": "must not",
"mustn't've": "must not have",
"needn't": "need not",
"needn't've": "need not have",
"o'clock": "of the clock",
"oughtn't": "ought not",
"oughtn't've": "ought not have",
"shan't": "shall not",
"sha'n't": "shall not",
"shan't've": "shall not have",
"she'd": "she had",
"she'd've": "she would have",
"she'll": "she will",
"she'll've": "she shall have / she will have",
"she's": "she is",
"should've": "should have",
"shouldn't": "should not",
"shouldn't've": "should not have",
"so've": "so have",
"so's": "so is",
"that'd": "that would",
"that'd've": "that would have",
"that's": "that is",
"there'd": "there had",
"there'd've": "there would have",
"there's": "there is",
"they'd": "they had",
"they'd've": "they would have",
"they'll": "they will",
"they'll've": "they shall have / they will have",
"they're": "they are",
"they've": "they have",
"to've": "to have",
"wasn't": "was not",
"we'd": "we would",
"we'd've": "we would have",
"we'll": "we will",
"we'll've": "we will have",
"we're": "we are",
"we've": "we have",
"weren't": "were not",
"what'll": "what will",
"what'll've": "what shall have / what will have",
"what're": "what are",
"what's": "what is",
"what've": "what have",
"when's": "when is",
"when've": "when have",
"where'd": "where did",
"where's": "where is",
"where've": "where have",
"who'll": "who will",
"who'll've": "who shall have / who will have",
"who's": "who is",
"who've": "who have",
"why's": "why is",
"why've": "why have",
"will've": "will have",
"won't": "will not",
"won't've": "will not have",
"would've": "would have",
"wouldn't": "would not",
"wouldn't've": "would not have",
"y'all": "you all",
"y'all'd": "you all would",
"y'all'd've": "you all would have",
"y'all're": "you all are",
"y'all've": "you all have",
"you'd": "you would",
"you'd've": "you would have",
"you'll": "you will",
"you'll've": "you shall have / you will have",
"you're": "you are",
"you've": "you have",
"It's":"it is", "doesn't":"does not"
}

In [13]:
Train['m_split'] = Train['message'].apply(lambda x: x.split())

In [14]:
Train.head()

sentiment                                            message  tweetid  \
0          1  PolySciMajor EPA chief doesn't think carbon di...   625221   
1          1  It's not like we lack evidence of anthropogeni...   126103   
2          2  RT @RawStory: Researchers say we have three ye...   698562   
3          1  #TodayinMaker# WIRED : 2016 was a pivotal year...   573736   
4          1  RT @SoyNovioDeTodas: It's 2016, and a racist, ...   466954   

             @mentions          hashtags  \
0          [@mashable]               NaN   
1                  NaN               NaN   
2         [@rawstory:]               NaN   
3                  NaN  [#todayinmaker#]   
4  [@soynoviodetodas:]  [#electionnight]   

                                             m_split  
0  [PolySciMajor, EPA, chief, doesn't, think, car...  
1  [It's, not, like, we, lack, evidence, of, anth...  
2  [RT, @RawStory:, Researchers, say, we, have, t...  
3  [#TodayinMaker#, WIRED, :, 2016, was, a, pivot...  
4  [RT, @SoyNovioDeTodas:, It's, 2016,, and, a, r...

In [15]:
x = Train.iloc[0]['message']

In [16]:
x

"PolySciMajor EPA chief doesn't think carbon dioxide is main cause of global warming and.. wait, what!? https://t.co/yeLvcEFXkC via @mashable"

In [17]:
d = x.split()

In [18]:
for word in d:
    if word.lower() in contractions:
        x = x.replace(word, contractions[word.lower()])
print(x)

PolySciMajor EPA chief does not think carbon dioxide is main cause of global warming and.. wait, what!? https://t.co/yeLvcEFXkC via @mashable


In [19]:
def replace_apostrophe(x):
    d = x.split()
    for word in d:
        if word.lower() in contractions:
            x = x.replace(word, contractions[word.lower()])
        
    return x

In [20]:
replace_apostrophe(x)

'PolySciMajor EPA chief does not think carbon dioxide is main cause of global warming and.. wait, what!? https://t.co/yeLvcEFXkC via @mashable'

In [21]:
Train['message'] = Train['message'].apply(lambda c: replace_apostrophe(c))

In [22]:
Train

sentiment                                            message  tweetid  \
0              1  PolySciMajor EPA chief does not think carbon d...   625221   
1              1  it is not like we lack evidence of anthropogen...   126103   
2              2  RT @RawStory: Researchers say we have three ye...   698562   
3              1  #TodayinMaker# WIRED : 2016 was a pivotal year...   573736   
4              1  RT @SoyNovioDeTodas: it is 2016, and a racist,...   466954   
5              1  Worth a read whether you do or do not believe ...   425577   
6              1  RT @thenation: Mike Pence doesn’t believe in g...   294933   
7              1  RT @makeandmendlife: Six big things we can ALL...   992717   
8              1  @AceofSpadesHQ My 8yo nephew is inconsolable. ...   664510   
9              1  RT @paigetweedy: no offense… but like… how do ...   260471   
10             1  RT @StephenSchlegel: she is thinking about how...   295793   
11             1  I do hope people who are vocal about climate c...   763719   
12             2  RT @tveitdal: We only have a 5 percent chance ...   454673   
13             1  RT @Alifaith55: Oh. My. God.\n\nTrump's Govern...    41161   
14             2  Fossil fuel giant ExxonMobil ‘misled’ the publ...   658092   
15             1  RT @GlblCtzn: 'I do not wanna live forever – a...   319524   
16             1  RT @jackholmes0: Issues scrubbed from https://...   698009   
17             1  RT @patagonia: If our elected leaders fail to ...   490604   
18             1  RT @SenSanders: We have a president-elect who ...   228658   
19             0  Calum: *tweets abt reunitingish w the cast*\n-...   547924   
20             1  RT @c40cities: 46 C40 Mayors, representing 250...   625014   
21             1  RT @World_Wildlife: How climate change impacts...   690605   
22             0  we also met this guy, he let us in on some tru...    67545   
23             1  https://t.co/KyNIBjmDk5\nScientists say climat...   567842   
24             1  RT @TammyGrubb: Obama raises climate change. Y...   684492   
25             1  I hate to say this, but *mental* health will b...   438578   
26             2  Bangladesh confronting climate change head on ...   365291   
27             1  Hey There! Michael's vetted and approved marke...   387685   
28            -1  Sally Kohn’s latest evidence of climate change...   355491   
29             1  RT @StarTalkRadio: First: The public understan...   354015   
...          ...                                                ...      ...   
15789          1  Denying evidence of climate change is like fin...   530499   
15790          1  RT @CleanAirMoms_FL: .@DCCC fighting climate c...   618837   
15791          0  He is Instagramming about the dangers of globa...   410790   
15792          1  Trumps actions on climate change are an assaul...   970642   
15793          2  Suicides of nearly 60000 Indian farmers linked...     5456   
15794          1  Denying climate change is real, but so is dang...    62737   
15795          2  China’s coal use drops, showing commitment to ...   150587   
15796          2  RT @BreBarra: it is time to give up climate ch...   983654   
15797          0  @realDonaldTrump Damn China &amp; their climat...   650825   
15798          1  Dams raise global warming gas: SciDev https://...   863077   
15799          1  RT @SethMacFarlane: HRC proposes installing ha...    52528   
15800          1  RT @sapinker: The only practical way to avert ...   580806   
15801          1  RT @SenSanders: On virtually every major issue...   331127   
15802          2  Michael Bloomberg to world leaders: ignore Tru...   585908   
15803          2  Suicides of nearly 60,000 Indian farmers linke...   296403   
15804          1  RT @cathdweeb: me with full knowledge of globa...   386076   
15805          2  RT @GrindTV: New head of EPA says climate chan...   830383   
15806         -1  RT @HerberMp: @sness5561_ness Al Gore is a idi...   213863   
15807  

In [23]:
df = Train[['sentiment', 'message']]

In [24]:
df.head()

sentiment                                            message
0          1  PolySciMajor EPA chief does not think carbon d...
1          1  it is not like we lack evidence of anthropogen...
2          2  RT @RawStory: Researchers say we have three ye...
3          1  #TodayinMaker# WIRED : 2016 was a pivotal year...
4          1  RT @SoyNovioDeTodas: it is 2016, and a racist,...

In [25]:
import re
text = df.message[3]

In [26]:
text

'#TodayinMaker# WIRED : 2016 was a pivotal year in the war on climate change https://t.co/44wOTxTLcD'

In [27]:
re.sub(r'@[A-Za-z0-9]+','',text)

'#TodayinMaker# WIRED : 2016 was a pivotal year in the war on climate change https://t.co/44wOTxTLcD'

In [28]:
re.sub(r'https?://[A-Za-z0-9./]+','',text)

'#TodayinMaker# WIRED : 2016 was a pivotal year in the war on climate change '

In [29]:
re.sub(r'#[A-Za-z0-9]+','',text)

'# WIRED : 2016 was a pivotal year in the war on climate change https://t.co/44wOTxTLcD'

In [30]:
def clean_text(text):
    import string
    text.lower()
    text = re.sub(r'@[A-Za-z0-9]+','',text)
    text = re.sub(r'https?://[A-Za-z0-9./]+','',text)
    text = re.sub(r'#[A-Za-z0-9]+','',text)
    
    text = re.sub('\[.*?\]','',text)
    text = re.sub('[%s]' % re.escape(string.punctuation),'',text)
    text = re.sub('\w*\d\w*','',text)
    text = re.sub(r'[^a-zA-Z0-9 ]','',text)
    
    return text

In [31]:
df['message'] = df['message'].apply(lambda x: clean_text(x))

C:\Users\Dell\Anaconda3\envs\nlp_course\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.


In [32]:
df.head()

sentiment                                            message
0          1  PolySciMajor EPA chief does not think carbon d...
1          1  it is not like we lack evidence of anthropogen...
2          2  RT  Researchers say we have three years to act...
3          1   WIRED   was a pivotal year in the war on clim...
4          1  RT  it is  and a racist sexist climate change ...

In [33]:
def clean_text2(text):
    text = re.sub('[''""...]','',text)
    text = re.sub('\n','',text)
    return text

In [34]:
df.message = df.message.apply(lambda x: clean_text2(x))
df.message = df.message.apply(lambda x: x.lower())

C:\Users\Dell\Anaconda3\envs\nlp_course\lib\site-packages\pandas\core\generic.py:4405: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self[name] = value


In [35]:
df.head()

sentiment                                            message
0          1  polyscimajor epa chief does not think carbon d...
1          1  it is not like we lack evidence of anthropogen...
2          2  rt  researchers say we have three years to act...
3          1   wired   was a pivotal year in the war on clim...
4          1  rt  it is  and a racist sexist climate change ...

In [36]:
X = df['message']
y = df['sentiment']

In [37]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test =train_test_split(X,y, test_size=0.3, random_state=42)

In [38]:
from sklearn.pipeline  import Pipeline
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.svm import LinearSVC
from sklearn.linear_model import LogisticRegression

In [39]:
textclf = Pipeline([('tfidf', TfidfVectorizer()),('clf', LinearSVC())])
textclf.fit(X_train,y_train)

Pipeline(steps=[('tfidf', TfidfVectorizer()), ('clf', LinearSVC())])

In [40]:
pred = textclf.predict(X_test)

In [41]:
from sklearn.metrics import confusion_matrix,classification_report, accuracy_score

In [42]:
print(confusion_matrix(y_test,pred))

[[ 161   56  160   24]
 [  28  289  286   63]
 [  46  135 2198  219]
 [   7   27  266  781]]


In [43]:
print(classification_report(y_test,pred))

              precision    recall  f1-score   support

          -1       0.67      0.40      0.50       401
           0       0.57      0.43      0.49       666
           1       0.76      0.85      0.80      2598
           2       0.72      0.72      0.72      1081

    accuracy                           0.72      4746
   macro avg       0.68      0.60      0.63      4746
weighted avg       0.71      0.72      0.71      4746



In [44]:
print(accuracy_score(y_test,pred))

0.7225031605562579


In [45]:
logistic = Pipeline([('tfidf', TfidfVectorizer()),('clf', LogisticRegression(multi_class='auto'))])

In [46]:
logistic.fit(X_train,y_train)

C:\Users\Dell\Anaconda3\envs\nlp_course\lib\site-packages\sklearn\linear_model\_logistic.py:764: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


Pipeline(steps=[('tfidf', TfidfVectorizer()), ('clf', LogisticRegression())])

In [47]:
pred1 = logistic.predict(X_test)

In [48]:
from sklearn.metrics import confusion_matrix,classification_report, accuracy_score

In [49]:
print(confusion_matrix(y_test,pred1))

[[ 101   60  220   20]
 [  13  233  360   60]
 [  10   76 2329  183]
 [   3   12  300  766]]


In [50]:
print(classification_report(y_test,pred1))

              precision    recall  f1-score   support

          -1       0.80      0.25      0.38       401
           0       0.61      0.35      0.45       666
           1       0.73      0.90      0.80      2598
           2       0.74      0.71      0.73      1081

    accuracy                           0.72      4746
   macro avg       0.72      0.55      0.59      4746
weighted avg       0.72      0.72      0.70      4746



In [51]:
print(accuracy_score(y_test,pred1))

0.7225031605562579


In [52]:
from sklearn.ensemble import RandomForestClassifier

ranForest = Pipeline([('tfidf', TfidfVectorizer()),('clf', RandomForestClassifier())])

In [53]:
ranForest.fit(X_train,y_train)

Pipeline(steps=[('tfidf', TfidfVectorizer()),
                ('clf', RandomForestClassifier())])

In [54]:
pred2 = ranForest.predict(X_test)

In [55]:
print(confusion_matrix(y_test,pred2))

[[  55   35  301   10]
 [   2  186  439   39]
 [   1   60 2364  173]
 [   1   23  357  700]]


In [56]:
print(classification_report(y_test,pred2))

              precision    recall  f1-score   support

          -1       0.93      0.14      0.24       401
           0       0.61      0.28      0.38       666
           1       0.68      0.91      0.78      2598
           2       0.76      0.65      0.70      1081

    accuracy                           0.70      4746
   macro avg       0.75      0.49      0.53      4746
weighted avg       0.71      0.70      0.66      4746



In [57]:
print(accuracy_score(y_test,pred2))

0.6963758954909397


In [58]:
from sklearn.naive_bayes import MultinomialNB

In [59]:
bayes = Pipeline([('tfidf', TfidfVectorizer()),('clf', MultinomialNB())])

In [60]:
bayes.fit(X_train,y_train)

Pipeline(steps=[('tfidf', TfidfVectorizer()), ('clf', MultinomialNB())])

In [61]:
pred3 = bayes.predict(X_test)

In [62]:
print(confusion_matrix(y_test,pred3))

[[   1    0  389   11]
 [   0   42  610   14]
 [   0    0 2555   43]
 [   0    0  627  454]]


In [63]:
print(classification_report(y_test,pred3))

              precision    recall  f1-score   support

          -1       1.00      0.00      0.00       401
           0       1.00      0.06      0.12       666
           1       0.61      0.98      0.75      2598
           2       0.87      0.42      0.57      1081

    accuracy                           0.64      4746
   macro avg       0.87      0.37      0.36      4746
weighted avg       0.76      0.64      0.56      4746



In [64]:
print(accuracy_score(y_test,pred3))

0.6430678466076696


In [65]:
from sklearn.linear_model import SGDClassifier

SGD = Pipeline([('tfidf', TfidfVectorizer()),('clf', SGDClassifier(loss='hinge', penalty='l2', tol=None))])

In [66]:
SGD.fit(X_train,y_train)

Pipeline(steps=[('tfidf', TfidfVectorizer()), ('clf', SGDClassifier(tol=None))])

In [67]:
pred4 = SGD.predict(X_test)

In [68]:
print(confusion_matrix(y_test,pred4))
print(classification_report(y_test,pred4))
print(accuracy_score(y_test,pred4))

[[ 141   48  186   26]
 [  16  241  345   64]
 [  25   74 2283  216]
 [   7   21  273  780]]
              precision    recall  f1-score   support

          -1       0.75      0.35      0.48       401
           0       0.63      0.36      0.46       666
           1       0.74      0.88      0.80      2598
           2       0.72      0.72      0.72      1081

    accuracy                           0.73      4746
   macro avg       0.71      0.58      0.62      4746
weighted avg       0.72      0.73      0.71      4746

0.7258744205646861


In [89]:
from imblearn.datasets import make_imbalance
from imblearn.under_sampling import NearMiss,InstanceHardnessThreshold
from imblearn.pipeline import make_pipeline
from imblearn.metrics import classification_report_imbalanced

In [101]:
pipeline = make_pipeline((TfidfVectorizer()),NearMiss(sampling_strategy='auto',version=2),
                         LogisticRegression())
pipeline.fit(X_train, y_train)

Pipeline(steps=[('tfidfvectorizer', TfidfVectorizer()),
                ('nearmiss', NearMiss(version=2)),
                ('logisticregression', LogisticRegression())])

In [102]:
from sklearn import metrics

# Create a prediction set:
predictions = pipeline.predict(X_test)

# Print a confusion matrix
print(metrics.confusion_matrix(y_test,predictions))

[[ 269   65   43   24]
 [ 119  340  105  102]
 [ 298  373 1448  479]
 [  32   52  105  892]]


In [103]:
print(metrics.classification_report(y_test,predictions))

              precision    recall  f1-score   support

          -1       0.37      0.67      0.48       401
           0       0.41      0.51      0.45       666
           1       0.85      0.56      0.67      2598
           2       0.60      0.83      0.69      1081

    accuracy                           0.62      4746
   macro avg       0.56      0.64      0.58      4746
weighted avg       0.69      0.62      0.63      4746

